#![allow(unused_imports)]

use prost::Message;
use rinf::{
    debug_print, send_rust_signal, signal_channel,
    DartSignal, SignalReceiver, SignalSender,
};
use std::sync::LazyLock;


// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountData {
    #[prost(string, tag="1")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
}
/// \[DART-SIGNAL\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsoAccountLoginInput {
    #[prost(message, optional, tag="1")]
    pub account: ::core::option::Option<AccountData>,
}
/// \[DART-SIGNAL\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EduAccountLoginInput {
    #[prost(message, optional, tag="1")]
    pub account: ::core::option::Option<AccountData>,
}
/// \[RUST-SIGNAL\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountLoginCallback {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, optional, tag="3")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)

type SSOAccountLoginInputChannel = LazyLock<(
    SignalSender<DartSignal<SsoAccountLoginInput>>,
    SignalReceiver<DartSignal<SsoAccountLoginInput>>,
)>;
pub static S_S_O_ACCOUNT_LOGIN_INPUT_CHANNEL: SSOAccountLoginInputChannel =
    LazyLock::new(signal_channel);

impl SsoAccountLoginInput {
    pub fn get_dart_signal_receiver() -> SignalReceiver<DartSignal<Self>> {
        S_S_O_ACCOUNT_LOGIN_INPUT_CHANNEL.1.clone()
    }
}

type EDUAccountLoginInputChannel = LazyLock<(
    SignalSender<DartSignal<EduAccountLoginInput>>,
    SignalReceiver<DartSignal<EduAccountLoginInput>>,
)>;
pub static E_D_U_ACCOUNT_LOGIN_INPUT_CHANNEL: EDUAccountLoginInputChannel =
    LazyLock::new(signal_channel);

impl EduAccountLoginInput {
    pub fn get_dart_signal_receiver() -> SignalReceiver<DartSignal<Self>> {
        E_D_U_ACCOUNT_LOGIN_INPUT_CHANNEL.1.clone()
    }
}

impl AccountLoginCallback {
    pub fn send_signal_to_dart(&self) {
        let result = send_rust_signal(
            3,
            self.encode_to_vec(),
            Vec::new(),
        );
        if let Err(error) = result {
            debug_print!("{error}\n{self:?}");
        }
    }
}
