#![allow(unused_imports)]

use prost::Message;
use rinf::{
    debug_print, send_rust_signal, signal_channel,
    DartSignal, SignalReceiver, SignalSender,
};
use std::sync::LazyLock;


// @generated
// This file is @generated by prost-build.
/// \[DART-SIGNAL\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LabDurationUserInput {
    #[prost(message, optional, tag="1")]
    pub account: ::core::option::Option<super::account::AccountData>,
    #[prost(int32, tag="2")]
    pub count: i32,
}
/// \[RUST-SIGNAL\]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LabDurationUserOutput {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, optional, tag="2")]
    pub err: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)

type LabDurationUserInputChannel = LazyLock<(
    SignalSender<DartSignal<LabDurationUserInput>>,
    SignalReceiver<DartSignal<LabDurationUserInput>>,
)>;
pub static LAB_DURATION_USER_INPUT_CHANNEL: LabDurationUserInputChannel =
    LazyLock::new(signal_channel);

impl LabDurationUserInput {
    pub fn get_dart_signal_receiver() -> SignalReceiver<DartSignal<Self>> {
        LAB_DURATION_USER_INPUT_CHANNEL.1.clone()
    }
}

impl LabDurationUserOutput {
    pub fn send_signal_to_dart(&self) {
        let result = send_rust_signal(
            21,
            self.encode_to_vec(),
            Vec::new(),
        );
        if let Err(error) = result {
            debug_print!("{error}\n{self:?}");
        }
    }
}
